import type { MockEventSeed, RawEvent } from "@/lib/events/types";
import { env } from "@/lib/config/env";
import type { EventSourceProvider, FetchEventsInput } from "./provider";

const now = new Date("2026-06-19T12:00:00.000Z");

function iso(daysFromNow: number, hour: number, minute = 0) {
  const date = new Date(now);
  date.setUTCDate(date.getUTCDate() + daysFromNow);
  date.setUTCHours(hour, minute, 0, 0);
  return date.toISOString();
}

const communitySeeds: MockEventSeed[] = [
  {
    id: "community-1",
    title: "Tech Meetup",
    description: "A casual Rhinegeist meetup for builders, founders, and new-in-town technologists.",
    startDateTime: iso(2, 22),
    endDateTime: iso(3, 0),
    timezone: "America/New_York",
    venueName: "Rhinegeist Brewery",
    address: "1910 Elm St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Over-the-Rhine",
    latitude: 39.1134,
    longitude: -84.5191,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/tech-meetup",
    sourceEventId: "community-source-1",
    imageUrl: null,
    categories: ["tech", "networking"]
  },
  {
    id: "community-2",
    title: "Tech Meet-up",
    description: "A neighborhood tech mixer listed by a second community volunteer.",
    startDateTime: iso(2, 22),
    endDateTime: iso(3, 0),
    timezone: "America/New_York",
    venueName: "Rhinegeist Brewery",
    address: "1910 Elm St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Over-the-Rhine",
    latitude: 39.1134,
    longitude: -84.5191,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/tech-meet-up",
    sourceEventId: "community-source-2",
    imageUrl: null,
    categories: ["tech", "community"]
  },
  {
    id: "community-3",
    title: "Cincinnati Tech Meetup",
    description: "A Rhinegeist community posting for the same tech social.",
    startDateTime: iso(11, 22),
    endDateTime: iso(12, 0),
    timezone: "America/New_York",
    venueName: "Rhinegeist Brewery",
    address: "1910 Elm St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Over-the-Rhine",
    latitude: 39.1134,
    longitude: -84.5191,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/cincinnati-tech-meetup",
    sourceEventId: "community-source-3",
    imageUrl: null,
    categories: ["tech", "business"]
  },
  {
    id: "community-4",
    title: "Tech Meetup at Rhinegeist",
    description: "Same-night listing with the venue highlighted in the title.",
    startDateTime: iso(20, 22),
    endDateTime: iso(21, 0),
    timezone: "America/New_York",
    venueName: "Rhinegeist Brewery",
    address: "1910 Elm St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Over-the-Rhine",
    latitude: 39.1134,
    longitude: -84.5191,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/tech-meetup-rhinegeist",
    sourceEventId: "community-source-4",
    imageUrl: null,
    categories: ["tech", "networking", "startup"]
  },
  {
    id: "community-5",
    title: "Jazz Under the Bridge Live Set",
    description: "A community calendar variant of the riverfront jazz night.",
    startDateTime: iso(6, 23),
    endDateTime: iso(7, 1),
    timezone: "America/New_York",
    venueName: "Sawyer Point",
    address: "705 E Pete Rose Way",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Riverfront",
    latitude: 39.0968,
    longitude: -84.4989,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/jazz-under-bridge-live-set",
    sourceEventId: "community-source-5",
    imageUrl: null,
    categories: ["music", "culture"]
  },
  {
    id: "community-6",
    title: "Public Square Night Market at Court Street",
    description: "Food stalls and local makers in a community calendar version of the market.",
    startDateTime: iso(3, 22),
    endDateTime: iso(4, 1),
    timezone: "America/New_York",
    venueName: "Court Street Plaza",
    address: "641 Walnut St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Downtown",
    latitude: 39.1037,
    longitude: -84.5122,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/court-street-night-market",
    sourceEventId: "community-source-6",
    imageUrl: null,
    categories: ["markets", "food-drink"]
  },
  {
    id: "community-7",
    title: "Sunset Run Club at the Riverfront",
    description: "A runner-submitted listing for the same sunset social run.",
    startDateTime: iso(0, 23),
    endDateTime: iso(1, 0),
    timezone: "America/New_York",
    venueName: "Smale Riverfront Park",
    address: "166 W Mehring Way",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Downtown",
    latitude: 39.0977,
    longitude: -84.5166,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/sunset-run-club-riverfront",
    sourceEventId: "community-source-7",
    imageUrl: null,
    categories: ["fitness", "outdoors", "wellness"]
  },
  {
    id: "community-8",
    title: "Neighborhood Film on the Lawn",
    description: "Bring a blanket for an outdoor movie with food trucks and newcomer hosts.",
    startDateTime: iso(4, 1),
    endDateTime: iso(4, 3),
    timezone: "America/New_York",
    venueName: "Washington Park",
    address: "1230 Elm St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Over-the-Rhine",
    latitude: 39.1095,
    longitude: -84.5164,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/neighborhood-film-lawn",
    sourceEventId: "community-source-8",
    imageUrl: null,
    categories: ["film", "community", "outdoors"]
  },
  {
    id: "community-9",
    title: "Volunteer River Cleanup Morning",
    description: "Meet neighbors while helping tidy the riverfront trail.",
    startDateTime: iso(5, 13),
    endDateTime: iso(5, 16),
    timezone: "America/New_York",
    venueName: "Yeatman's Cove",
    address: "705 E Pete Rose Way",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Riverfront",
    latitude: 39.0962,
    longitude: -84.5038,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/volunteer-river-cleanup",
    sourceEventId: "community-source-9",
    imageUrl: null,
    categories: ["community", "outdoors"]
  },
  {
    id: "community-10",
    title: "Global Bites Pop-Up Dinner",
    description: "A rotating chef dinner with communal tables and neighborhood guides.",
    startDateTime: iso(8, 23),
    endDateTime: iso(9, 1),
    timezone: "America/New_York",
    venueName: "Findlay Kitchen",
    address: "1719 Elm St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Over-the-Rhine",
    latitude: 39.1153,
    longitude: -84.5194,
    priceType: "paid",
    minPrice: 22,
    maxPrice: 28,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/global-bites-pop-up-dinner",
    sourceEventId: "community-source-10",
    imageUrl: null,
    categories: ["food-drink", "community"]
  },
  {
    id: "community-11",
    title: "Board Game Brunch for New Neighbors",
    description: "Hosted tables and easy-to-learn games over brunch.",
    startDateTime: iso(9, 16),
    endDateTime: iso(9, 19),
    timezone: "America/New_York",
    venueName: "OTR StillHouse",
    address: "2017 Branch St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Over-the-Rhine",
    latitude: 39.113,
    longitude: -84.5206,
    priceType: "paid",
    minPrice: 8,
    maxPrice: 15,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/board-game-brunch",
    sourceEventId: "community-source-11",
    imageUrl: null,
    categories: ["gaming", "food-drink", "community"]
  },
  {
    id: "community-12",
    title: "Neighborhood Makers Demo Day",
    description: "A free showcase of local side projects, zines, and prototypes.",
    startDateTime: iso(10, 22),
    endDateTime: iso(11, 0),
    timezone: "America/New_York",
    venueName: "Esoteric Brewing",
    address: "918 E McMillan St",
    city: "Cincinnati",
    region: "OH",
    country: "USA",
    neighborhood: "Walnut Hills",
    latitude: 39.1288,
    longitude: -84.4909,
    priceType: "free",
    minPrice: null,
    maxPrice: null,
    currency: "USD",
    sourceId: "community-mock",
    sourceName: "Community Calendar Mock",
    sourceType: "mock",
    sourceUrl: "https://community.example.com/events/makers-demo-day",
    sourceEventId: "community-source-12",
    imageUrl: null,
    categories: ["arts", "tech", "community"]
  }
];

async function fetchCommunityMockEvents(input: FetchEventsInput): Promise<RawEvent[]> {
  return communitySeeds
    .filter((seed) => seed.city.toLowerCase() === input.city.toLowerCase())
    .map((seed) => ({
      sourceId: seed.sourceId,
      sourceName: seed.sourceName,
      sourceType: seed.sourceType,
      sourceEventId: seed.sourceEventId,
      sourceUrl: seed.sourceUrl,
      fetchedAt: new Date("2026-06-19T12:00:00.000Z").toISOString(),
      raw: seed
    }));
}

export const communityMockProvider: EventSourceProvider = {
  sourceId: "community-mock",
  sourceName: "Community Calendar Mock",
  sourceType: "mock",
  enabled: env.enableCommunityMockProvider,
  fetchEvents: fetchCommunityMockEvents
};
