INSERT INTO events (
  title,
  description,
  start_time,
  end_time,
  timezone,
  venue_name,
  address,
  location,
  city,
  region,
  categories,
  price_type,
  source,
  source_family,
  source_url,
  source_event_id,
  engagement_signals,
  confidence_score,
  publish_state,
  verification_count,
  verified_by_trusted_source,
  verification_reasons,
  ingested_at,
  last_seen_at,
  provenance_source_ids
)
VALUES
(
  'Sample Music Night',
  'Local jazz artists and food vendors.',
  NOW() + INTERVAL '6 hours',
  NOW() + INTERVAL '9 hours',
  'America/New_York',
  'Fountain Square Stage',
  '520 Vine St, Cincinnati, OH',
  ST_SetSRID(ST_MakePoint(-84.512, 39.103), 4326),
  'Cincinnati',
  'OH',
  ARRAY['music', 'food'],
  'free',
  'seed_city_calendar',
  'calendar',
  'https://example.com/events/sample-1',
  'seed_api_1',
  '{"likes": 120, "comments": 14}',
  0.86,
  'published',
  2,
  TRUE,
  ARRAY['trusted calendar source', 'cross-confirmed by listing'],
  NOW(),
  NOW(),
  ARRAY['seed_api_1']
)
ON CONFLICT (source, source_event_id) DO NOTHING;
